import 'package:flutter/material.dart';

final ValueNotifier<String> appLanguage = ValueNotifier<String>('en'); 

class AppTexts {
  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'welcome': 'Welcome,',
      'dashboard_title': 'Dashboard - Stockly',
      'items': 'Items & Categories',
      'add_batch': 'Add Batch',
      'fefo_withdraw': 'Withdraw (FEFO)',
      'history': 'History & Logs',
      'reports': 'Reports',
      'settings': 'Settings',
      'settings_title': 'System & Security Settings',
      'change_pin': 'Change PIN',
      'change_pin_sub': 'Update Stockly access code',
      'backup': 'Backup',
      'backup_sub': 'Save a secure copy of inventory data',
      'appearance': 'Appearance',
      'appearance_sub': 'Enable Dark Mode',
      'app_language': 'App Language',
      'app_language_sub': 'English (Default)',
      'lock_app': 'Lock App',
      'choose_language': 'Choose Language',
      'cancel': 'Cancel',
      'reports_overview': 'Inventory Overview',
      'total_items': 'Total Items',
      'total_items_sub': '45 registered items',
      'shortages': 'Stock Shortages',
      'shortages_sub': '3 items below minimum',
      'expiry_alerts': 'Expiry Alerts (FEFO)',
      'expiry_alerts_sub': '2 batches nearing expiry',
      'today_movement': 'Today\'s Movement',
      'today_movement_sub': '12 operations (In/Out)',
      'search_item': 'Search items...',
      'add_new_item': 'Add New Item',
      'select_item': 'Select Item',
      'batch_number': 'Batch/Lot Number',
      'quantity': 'Quantity',
      'expiry_date': 'Expiry Date',
      'select_date': 'Select Date',
      'no_date_selected': 'No date selected',
      'save_batch': 'Save Batch',
      'withdraw_qty': 'Withdrawal Quantity',
      'withdraw_btn': 'Withdraw Batch',
      'fefo_alert': 'Will be withdrawn from the closest expiry batch automatically.',
      // الحقول الجديدة للإشعارات
      'min_qty_alert': 'Minimum Quantity Alert',
      'min_expiry_alert': 'Expiry Alert Threshold (Months)',
    },
    'ar': {
      'welcome': 'مرحباً بك،',
      'dashboard_title': 'لوحة التحكم - Stockly',
      'items': 'الأصناف والفئات',
      'add_batch': 'إضافة دفعة',
      'fefo_withdraw': 'سحب (FEFO)',
      'history': 'السجل والفعاليات',
      'reports': 'التقارير',
      'settings': 'الإعدادات',
      'settings_title': 'إعدادات النظام والأمان',
      'change_pin': 'تغيير الرمز السري (PIN)',
      'change_pin_sub': 'تحديث رمز الدخول لتطبيق Stockly',
      'backup': 'النسخ الاحتياطي',
      'backup_sub': 'حفظ نسخة أمان من بيانات المخزون',
      'appearance': 'المظهر',
      'appearance_sub': 'تفعيل الوضع الداكن (Dark Mode)',
      'app_language': 'لغة التطبيق',
      'app_language_sub': 'العربية',
      'lock_app': 'قفل التطبيق',
      'choose_language': 'اختر اللغة',
      'cancel': 'إلغاء',
      'reports_overview': 'نظرة عامة على المخزون',
      'total_items': 'إجمالي الأصناف',
      'total_items_sub': '45 صنف مسجل',
      'shortages': 'نواقص المخزون',
      'shortages_sub': '3 أصناف تحت الحد الأدنى',
      'expiry_alerts': 'تنبيهات الصلاحية (FEFO)',
      'expiry_alerts_sub': 'دفعتان تقتربان من الانتهاء',
      'today_movement': 'حركة المخزن اليوم',
      'today_movement_sub': '12 عملية (دخول/خروج)',
      'search_item': 'ابحث عن صنف...',
      'add_new_item': 'إضافة صنف جديد',
      'select_item': 'اختر الصنف',
      'batch_number': 'رقم التشغيلة (Batch/Lot)',
      'quantity': 'الكمية المدخلة',
      'expiry_date': 'تاريخ الانتهاء',
      'select_date': 'اختر التاريخ',
      'no_date_selected': 'تاريخ الانتهاء غير محدد',
      'save_batch': 'حفظ الدفعة',
      'withdraw_qty': 'الكمية المراد سحبها',
      'withdraw_btn': 'سحب الدفعة',
      'fefo_alert': 'سيتم السحب من الدفعة الأقرب انتهاءً تلقائياً.',
      // الحقول الجديدة للإشعارات
      'min_qty_alert': 'أقل كمية للإشعار',
      'min_expiry_alert': 'أقل تاريخ انتهاء للإشعار (بالأشهر)',
    },
    'de': {
      'welcome': 'Willkommen,',
      'dashboard_title': 'Dashboard - Stockly',
      'items': 'Artikel & Kategorien',
      'add_batch': 'Charge hinzufügen',
      'fefo_withdraw': 'Entnahme (FEFO)',
      'history': 'Verlauf & Protokolle',
      'reports': 'Berichte',
      'settings': 'Einstellungen',
      'settings_title': 'System- & Sicherheitseinstellungen',
      'change_pin': 'PIN ändern',
      'change_pin_sub': 'Zugangscode für Stockly aktualisieren',
      'backup': 'Sicherung (Backup)',
      'backup_sub': 'Sichere Kopie der Bestandsdaten speichern',
      'appearance': 'Erscheinungsbild',
      'appearance_sub': 'Dunkelmodus aktivieren',
      'app_language': 'App-Sprache',
      'app_language_sub': 'Deutsch',
      'lock_app': 'App sperren',
      'choose_language': 'Sprache wählen',
      'cancel': 'Abbrechen',
      'reports_overview': 'Bestandsübersicht',
      'total_items': 'Gesamtartikel',
      'total_items_sub': '45 registrierte Artikel',
      'shortages': 'Bestandsengpässe',
      'shortages_sub': '3 Artikel unter Minimum',
      'expiry_alerts': 'Ablaufwarnungen (FEFO)',
      'expiry_alerts_sub': '2 Chargen vor Ablauf',
      'today_movement': 'Heutige Bewegung',
      'today_movement_sub': '12 Vorgänge (Ein/Aus)',
      'search_item': 'Artikel suchen...',
      'add_new_item': 'Neuen Artikel hinzufügen',
      'select_item': 'Artikel auswählen',
      'batch_number': 'Chargennummer (Lot)',
      'quantity': 'Menge',
      'expiry_date': 'Ablaufdatum',
      'select_date': 'Datum auswählen',
      'no_date_selected': 'Kein Datum ausgewählt',
      'save_batch': 'Charge speichern',
      'withdraw_qty': 'Entnahmemenge',
      'withdraw_btn': 'Charge entnehmen',
      'fefo_alert': 'Wird automatisch von der Charge mit dem nächsten Ablaufdatum entnommen.',
      // الحقول الجديدة للإشعارات
      'min_qty_alert': 'Mindestmengenalarm',
      'min_expiry_alert': 'Ablaufwarnung (Monate)',
    }
  };

  static String get(String key) {
    return _translations[appLanguage.value]?[key] ?? key;
  }

  static TextDirection getDirection() {
    return appLanguage.value == 'ar' ? TextDirection.rtl : TextDirection.ltr;
  }
}